import jsPDF from 'jspdf';
import { Color, ColorPalette } from '../types';

export class ExportUtils {
  static async exportAsPNG(colors: Color[], name: string): Promise<void> {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d')!;
    
    const swatchWidth = 120;
    const swatchHeight = 120;
    const padding = 15;
    const textHeight = 80;
    
    canvas.width = colors.length * (swatchWidth + padding) - padding;
    canvas.height = swatchHeight + textHeight;
    
    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    colors.forEach((color, index) => {
      const x = index * (swatchWidth + padding);
      
      // Color swatch with rounded corners effect
      ctx.fillStyle = color.hex;
      ctx.fillRect(x, 0, swatchWidth, swatchHeight);
      
      // Add subtle border
      ctx.strokeStyle = '#e5e5e5';
      ctx.lineWidth = 1;
      ctx.strokeRect(x, 0, swatchWidth, swatchHeight);
      
      // Hex code text
      ctx.fillStyle = '#1f2937';
      ctx.font = 'bold 14px Arial';
      ctx.textAlign = 'center';
      ctx.fillText(color.hex.toUpperCase(), x + swatchWidth / 2, swatchHeight + 25);
      
      // RGB text
      ctx.font = '12px Arial';
      ctx.fillStyle = '#6b7280';
      ctx.fillText(
        `RGB(${color.rgb.join(', ')})`,
        x + swatchWidth / 2,
        swatchHeight + 45
      );
      
      // HSL text
      ctx.fillText(
        `HSL(${color.hsl[0]}°, ${color.hsl[1]}%, ${color.hsl[2]}%)`,
        x + swatchWidth / 2,
        swatchHeight + 65
      );
    });
    
    // Download
    canvas.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${name}-palette.png`;
        a.click();
        URL.revokeObjectURL(url);
      }
    });
  }

  static async exportAsPDF(colors: Color[], name: string): Promise<void> {
    const pdf = new jsPDF('landscape', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Title
    pdf.setFontSize(24);
    pdf.setTextColor(51, 51, 51);
    pdf.text(`${name} - Color Palette`, 20, 25);
    
    // Subtitle
    pdf.setFontSize(12);
    pdf.setTextColor(107, 114, 128);
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 35);
    
    const swatchWidth = 35;
    const swatchHeight = 35;
    const startX = 20;
    const startY = 50;
    const spacing = 45;
    
    colors.forEach((color, index) => {
      const x = startX + (index * spacing);
      const y = startY;
      
      // Color swatch
      const [r, g, b] = color.rgb;
      pdf.setFillColor(r, g, b);
      pdf.rect(x, y, swatchWidth, swatchHeight, 'F');
      
      // Border
      pdf.setDrawColor(229, 229, 229);
      pdf.setLineWidth(0.5);
      pdf.rect(x, y, swatchWidth, swatchHeight, 'S');
      
      // Color information
      pdf.setFontSize(10);
      pdf.setTextColor(31, 41, 55);
      
      // Hex
      pdf.text(color.hex.toUpperCase(), x + swatchWidth/2, y + swatchHeight + 8, { align: 'center' });
      
      // RGB
      pdf.setFontSize(8);
      pdf.setTextColor(107, 114, 128);
      pdf.text(`RGB(${color.rgb.join(', ')})`, x + swatchWidth/2, y + swatchHeight + 15, { align: 'center' });
      
      // HSL
      pdf.text(`HSL(${color.hsl[0]}°, ${color.hsl[1]}%, ${color.hsl[2]}%)`, x + swatchWidth/2, y + swatchHeight + 22, { align: 'center' });
    });
    
    // Color analysis section
    pdf.setFontSize(16);
    pdf.setTextColor(51, 51, 51);
    pdf.text('Color Analysis', 20, 130);
    
    pdf.setFontSize(10);
    pdf.setTextColor(107, 114, 128);
    
    colors.forEach((color, index) => {
      const yPos = 145 + (index * 15);
      pdf.text(`Color ${index + 1}:`, 25, yPos);
      pdf.text(`${color.hex.toUpperCase()}`, 55, yPos);
      pdf.text(`Frequency: ${(color.frequency * 100).toFixed(1)}%`, 85, yPos);
      
      // Lightness category
      const lightness = color.hsl[2];
      let category = '';
      if (lightness < 25) category = 'Very Dark';
      else if (lightness < 50) category = 'Dark';
      else if (lightness < 75) category = 'Light';
      else category = 'Very Light';
      
      pdf.text(`Lightness: ${category}`, 140, yPos);
    });
    
    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(156, 163, 175);
    pdf.text('Generated by Color Palette Extractor', pageWidth - 20, pageHeight - 10, { align: 'right' });
    
    pdf.save(`${name}-palette.pdf`);
  }
  
  static exportAsJSON(palette: ColorPalette): void {
    const data = JSON.stringify(palette, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${palette.name}-palette.json`;
    a.click();
    URL.revokeObjectURL(url);
  }
  
  static exportAsCSS(colors: Color[], name: string): void {
    const css = colors.map((color, index) => 
      `  --color-${name.toLowerCase().replace(/\s+/g, '-')}-${index + 1}: ${color.hex};`
    ).join('\n');
    
    const cssContent = `:root {\n${css}\n}\n\n/* Usage examples */\n${colors.map((color, index) => 
      `.bg-${name.toLowerCase().replace(/\s+/g, '-')}-${index + 1} { background-color: var(--color-${name.toLowerCase().replace(/\s+/g, '-')}-${index + 1}); }`
    ).join('\n')}`;
    
    const blob = new Blob([cssContent], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name}-palette.css`;
    a.click();
    URL.revokeObjectURL(url);
  }
  
  static copyToClipboard(text: string): void {
    navigator.clipboard.writeText(text);
  }
}